#$ -N achlys
#$ -q achlys.q
#$ -l h_rt=168:00:00
#$ -cwd
#$ -S /bin/bash
#export PATH=/opt/mgltools/1.5.4/bin:$PATH
export PATH=/opt/mgltools/1.5.4/MGLToolsPckgs/AutoDockTools/Utilities24:$PATH
export PATH=/opt/autodock/4.2.3/bin:$PATH
export PATH=/gluster/home/achlys/achlys/bin:$PATH
export PYTHONPATH=/opt/mgltools/1.5.4/MGLToolsPckgs:$PYTHONPATH
export PYTHONPATH=/gluster/home/achlys/achlys/lib/python2.7/site-packages:$PYTHONPATH
export AMBERHOME=/pmshare/amber/amber12-20120918
export PATH=$AMBERHOME/bin:$PATH
python /gluster/home/achlys/achlys/bin/tox \
    -l /gluster/home/achlys/achlys/sample/CR3/CR3_LP_PDB/colchicine.pdb \
    /gluster/home/achlys/achlys/sample/CR3/CR3_LP_PDB/CR-42-002.pdb \
    /gluster/home/achlys/achlys/sample/CR3/CR3_LP_PDB/CR-42-024.pdb \
    -r /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_01.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_02.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_03.pdb \
    -n 64 \
    --multi \
    -f config_PW.ini
