#$ -N achlys
#$ -q achlys.q
#$ -l h_rt=168:00:00
#$ -cwd
#$ -S /bin/bash
#export PATH=/opt/mgltools/1.5.4/bin:$PATH
export PATH=/opt/mgltools/1.5.4/MGLToolsPckgs/AutoDockTools/Utilities24:$PATH
export PATH=/opt/autodock/4.2.3/bin:$PATH
export PATH=/gluster/home/achlys/achlys/bin:$PATH
export PYTHONPATH=/opt/mgltools/1.5.4/MGLToolsPckgs:$PYTHONPATH
export PYTHONPATH=/gluster/home/achlys/achlys/lib/python2.7/site-packages:$PYTHONPATH
export AMBERHOME=/pmshare/amber/amber12-20120918
export PATH=$AMBERHOME/bin:$PATH
python /gluster/home/achlys/achlys/bin/tox \
    -l /gluster/home/achlys/achlys/sample/CR3/CR3_LP_PDB/colchicine.pdb \
    /gluster/home/achlys/achlys/sample/CR3/CR3_LP_PDB/CR-42-002.pdb \
    /gluster/home/achlys/achlys/sample/CR3/CR3_LP_PDB/CR-42-024.pdb \
    -r /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_01.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_02.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_03.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_04.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_05.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_06.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_07.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_08.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_09.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_10.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_11.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_12.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_13.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_14.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_15.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_16.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_17.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_18.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_19.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_20.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_21.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_22.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_23.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_24.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_25.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_26.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_27.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_28.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_29.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_30.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_31.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_32.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_33.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_34.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_35.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_36.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_37.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_38.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_39.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_40.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_41.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_42.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_43.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_44.pdb \
    /gluster/home/achlys/achlys/data/KB_HERG/PDB/hERG-conformations_45.pdb \
    -n 8 \
    --multi \
    -f config_PW.ini
